#!/usr/bin/env python3
"""aggregate_validation.py — regenerate docs/validation-status.md from shipped model data
plus submitted community validation reports.

Each report is a JSON file produced by ``atf-dsp-sdk validate --json`` (schema
``atf-dsp-sdk/hw-validation/1``). The base row for every model comes from the SDK's own
model registry; a model's Hardware-status column is then upgraded by the strongest report
seen for it:

    Direction A (PC-Tool oracle) passed  -> validated (community)
    Direction B (SDK write->read) passed -> round-trips (community)

The MATCH M 5.4DSP stays maintainer-validated regardless. Reports for a model with no
passing check leave it untested. Idempotent: re-run whenever reports land.

Usage:
    python tools/aggregate_validation.py [--reports DIR] [--out FILE]
    python tools/aggregate_validation.py --reports reports/ --check   # CI: fail if stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from atf_dsp.models import MODEL_AT01, model_info  # noqa: E402

DEFAULT_OUT = REPO_ROOT / "docs" / "validation-status.md"
SCHEMA = "atf-dsp-sdk/hw-validation/1"

_HEADER = """# Hardware validation status

Coverage of the ACO model range. **Param map** ships for every model; the
**channel overlay** (fluent labelled API) and **hardware status** are what
community validation fills in. See
[validating-your-device.md](validating-your-device.md) to contribute a report.

Legend — Hardware status: ✅ validated on real hardware · 🟡 round-trips only
(Direction B on the amp, semantics unconfirmed) · ⬜ untested. This table is
generated by `tools/aggregate_validation.py` from submitted
[hardware-validation issues](../../issues?q=label%3Ahardware-validation).
"""

_FOOTER = """
"48 kHz (assumed)" means the rate is the SDK's fallback, not confirmed for that
model (the MATCH/HELIX line is understood to be 48 kHz, but only the M 5.4DSP is
bench-confirmed). BRAX rates come from the device-file name and are trustworthy.
"""


def _load_reports(reports_dir: Optional[Path]) -> Dict[str, dict]:
    """model name -> {'a': bool, 'b': bool, 'n': int} aggregated across report files."""
    agg: Dict[str, dict] = {}
    if not reports_dir or not reports_dir.is_dir():
        return agg
    for path in sorted(reports_dir.glob("*.json")):
        try:
            doc = json.loads(path.read_text())
        except (OSError, ValueError):
            print(f"[!] skipping unreadable report: {path.name}", file=sys.stderr)
            continue
        if doc.get("schema") != SCHEMA:
            print(f"[!] skipping (wrong schema): {path.name}", file=sys.stderr)
            continue
        model = (doc.get("device") or {}).get("model")
        if not model:
            continue
        rec = agg.setdefault(model, {"a": False, "b": False, "n": 0})
        rec["n"] += 1
        for rep in doc.get("reports", []):
            if not rep.get("ok"):
                continue
            direction = rep.get("direction", "")
            if direction.startswith("Direction A"):
                rec["a"] = True
            elif direction.startswith("Direction B"):
                rec["b"] = True
    return agg


def _status(model: str, info: dict, rep: Optional[dict]) -> str:
    if info.get("hardware_confirmed"):
        return "✅ validated (2026-08)"
    if rep:
        if rep["a"]:
            return f"✅ validated (community, {rep['n']} report(s))"
        if rep["b"]:
            return f"🟡 round-trips (community, {rep['n']} report(s))"
    return "⬜ untested"


def render(reports_dir: Optional[Path]) -> str:
    agg = _load_reports(reports_dir)
    rows: List[str] = []
    for model in sorted(MODEL_AT01):
        info = model_info(model)
        fs, fsc = info["fs_hz"], info["fs_confirmed"]
        fs_s = f"{fs // 1000} kHz" + ("" if fsc else " (assumed)")
        overlay = "yes" if info["has_channel_model"] else "—"
        status = _status(model, info, agg.get(model))
        rows.append(f"| {model} | {fs_s} | yes | {overlay} | {status} |")
    table = ("| Model | Sample rate | Param map | Channel overlay | Hardware status |\n"
             "|---|---|---|---|---|\n" + "\n".join(rows))
    return _HEADER + "\n" + table + "\n" + _FOOTER


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--reports", metavar="DIR", help="directory of submitted report.json files")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output markdown (default docs/validation-status.md)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the output file is out of date (CI)")
    args = ap.parse_args(argv)

    content = render(Path(args.reports) if args.reports else None)
    out = Path(args.out)
    if args.check:
        current = out.read_text() if out.exists() else ""
        if current != content:
            print(f"[!] {out} is out of date — run tools/aggregate_validation.py", file=sys.stderr)
            return 1
        print(f"[=] {out} is up to date")
        return 0
    out.write_text(content)
    print(f"[+] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
